version: "3"

services:
  companyhero-api:
    container_name: companyhero-api
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/usr/app
    ports:
      - 3000:3000
    restart: "on-failure"